# Generated by Django 5.0.7 on 2026-03-26 09:51

from django.db import migrations, models


def empty_phone_to_null(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(phone="").update(phone=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_driver_license_number_alter_driver_national_id_and_more'),
    ]

    operations = [
        # Step 1: allow NULL first (no unique yet)
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        # Step 2: convert empty strings to NULL
        migrations.RunPython(empty_phone_to_null, migrations.RunPython.noop),
        # Step 3: add unique constraint
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
