# Generated by Django 5.0.7 on 2026-04-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_email_verified_user_failed_login_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='failed_login_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
