# Generated by Django 5.0.7 on 2026-05-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_backup_email_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_backup_password_reset',
            field=models.BooleanField(default=True),
        ),
    ]
