# Generated by Django — email privacy / reset preferences

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_allow_backup_password_reset"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="keep_email_private",
            field=models.BooleanField(
                default=True,
                help_text="When True, mask this user's emails for other non-admin API consumers.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="block_unverified_email_reset",
            field=models.BooleanField(
                default=True,
                help_text="When True, password-reset OTP to the primary email requires email_verified.",
            ),
        ),
    ]
