# Generated by Django 5.0.7 on 2026-03-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficsign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='signs/'),
        ),
    ]
