# Generated by Django 5.0.7 on 2026-02-28 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
        ('violations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_object', models.CharField(max_length=100)),
                ('confidence_score', models.FloatField()),
                ('image_url', models.URLField(blank=True)),
                ('detected_at', models.DateTimeField()),
                ('processed', models.BooleanField(default=False)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cameras.camera')),
                ('created_violation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='violations.trafficviolation')),
            ],
        ),
        migrations.CreateModel(
            name='LicensePlateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_plate', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField()),
                ('detected_at', models.DateTimeField()),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cameras.camera')),
            ],
        ),
    ]
