# Generated by Django 5.0.7 on 2026-02-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficviolation',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('warning', 'Warning')], default='medium', max_length=20),
        ),
    ]
