# Generated by Django 5.0.7 on 2026-03-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0002_trafficviolation_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficviolation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
